### ISSUE TITLE
The application breakdown when you try to mount the disk.

### ISSUE THREAD

**Issue by 4D4N-P** [balena-io-modules/node-ext2fs#95]
Error:
```
ErrnoException: node_ext2fs_mount UNKNOWN (2133571347) args: [1]
│      at ccallThrowAsync (path\to\project\node_modules\ext2fs\lib\util.js:41:9)
│      at async Object.exports.mount (path\to\project\node_modules\ext2fs\lib\ext2fs.js:18:15)
│      at async exports.withMountedDisk (path\to\project\node_modules\ext2fs\lib\ext2fs.js:41:13)
│      at async eval (webpack:///./src/main/index.js?:120:7)
│      at async withOpenFile (path\to\project\node_modules\file-disk\build\index.js:106:16)
│      at async writeFiles (webpack:///./src/main/index.js?:114:5) {
│    errno: 2133571347,
│    syscall: 'node_ext2fs_mount',
│    code: 'UNKNOWN'
│  }
```
Code:
`await withOpenFile(drivePath, 'r+', async (handle) => {`
I'm trying to mount the disk to record files on Windows 10 and get an error, while there is no this error on the MacOS. What should I do?

**Comment by ShaneMurphy2** [comment]
Same here, just running the example from the readme fails.
